{% set name = "pymbar" %}
{% set version = "3.0.5" %}
{% set sha256 = "a9bdfa37083757fe6ad83211a87aa18d51c04f8d87609752b86165a6e9730b98" %}

package:
  name: {{ name  }}
  version: {{ version }}

source:
  fn: {{ name}}-{{ version }}.tar.gz
  url: https://github.com/choderalab/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
    - six
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0.0
    - six
    - numexpr

test:
  requires:
    - nose
    - statsmodels
  imports:
    - pymbar
  commands:
    - nosetests pymbar --with-doctest --doctest-tests -v -I covariance

about:
  home: http://github.com/choderalab/pymbar
  dev_url: http://github.com/choderalab/pymbar
  doc_url: http://pymbar.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: 'Python implementation of the multistate Bennett acceptance ratio (MBAR) method.'

extra:
  recipe-maintainers:
    - Lnaden
    - jchodera
    - mrshirts
